server:
  port: 8401
spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111
    sentinel:
      transport:
        dashboard:localhost:8080
        port:8719
management:
  endpoint:
    web:
      exposure:
        incloud: "*"