spring:
  main:
    allow-bean-definition-overriding: true
#  security:
#    user:
#      name: admin
#      password: 123456
  profiles:
    active:
    - dev
  devtools:
    restart:
      enabled: true
      # additional-paths:
      # - src/main/java
      # exclude: "/web"
#  mail:
#    host: ""

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    env:
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        exclude:
          - "*"
#      base-path: "actuator"
#${random.int}
